version: '3.5'

services:
  milvus-standalone:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus-standalone
    restart: always
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    command: ["milvus", "run", "standalone"]

volumes:
  milvus_data:
